mariadb:
  host: ''
  username: ''
  password: ''
  synchronize: true

mongodb:
  host: 'mongodb://'

jwt:
  secret: 'Blackwhopper'

aws:
  bucket: ''
  region: ''
  acessKey: ''
  secretAccessKey: ''

session:
  secret: 'Blackwhopper'

ai:
  host: 'ws://'
