mariadb:
  host: '13.125.230.113'
  username: 'blackwhopper'
  password: 'qjrjzld@'
  synchronize: true

mongodb:
  host: 'mongodb://13.125.230.113:27017/vaiscan'

jwt:
  secret: 'Blackwhopper'

aws:
  bucket: 'vaiscanbox'
  region: 'ap-northeast-2'
  acessKey: 'AKIAZELXFW3RSRU53Y7T'
  secretAccessKey: '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'

session:
  secret: 'Blackwhopper'

ai:
  host: 'ws://192.168.123.103:8282'
