mariadb:
  host: '13.125.230.113'
  username: 'blackwhopper'
  password: 'qjrjzld@'
  synchronize: true

jwt:
  secret: 'Blackwhopper'

aws:
  region: 'ap-northeast-2'
  acessKey: 'AKIAZELXFW3RZGCAE47N'
  secretAccessKey: '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'

session:
  secret: 'Blackwhopper'
