mariadb:
  host: '3.35.205.173'
  username: 'blackwhopper'
  password: 'qjrjzld@'
  synchronize: true

staticAiServer:
  host: 'localhost'
  port: 8080

dynamicAiServer:
  host: 'localhost'
  port: 8080

jwt:
  secret: 'Blackwhopper'